[2025-06-06T20:20:34.048+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T20:20:25.822064+00:00/task_id=load_postgres permission to 509
[2025-06-06T20:20:34.049+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T20:20:25.822064+00:00/task_id=load_postgres permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T20:20:25.822064+00:00/task_id=load_postgres'
[2025-06-06T20:20:34.067+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T20:20:25.822064+00:00/task_id=load_postgres permission to 509
[2025-06-06T20:20:34.068+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T20:20:25.822064+00:00/task_id=load_postgres permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T20:20:25.822064+00:00/task_id=load_postgres'
[2025-06-06T20:20:34.093+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_music_pipeline.load_postgres manual__2025-06-06T20:20:25.822064+00:00 [queued]>
[2025-06-06T20:20:34.099+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_music_pipeline.load_postgres manual__2025-06-06T20:20:25.822064+00:00 [queued]>
[2025-06-06T20:20:34.099+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-06T20:20:34.108+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_postgres> on 2025-06-06 20:20:25.822064+00:00
[2025-06-06T20:20:34.113+0000] {standard_task_runner.py:60} INFO - Started process 339 to run task
[2025-06-06T20:20:34.115+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_music_pipeline', 'load_postgres', 'manual__2025-06-06T20:20:25.822064+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpwtv973k3']
[2025-06-06T20:20:34.116+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask load_postgres
[2025-06-06T20:20:34.155+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T20:20:25.822064+00:00/task_id=load_postgres permission to 509
[2025-06-06T20:20:34.155+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T20:20:25.822064+00:00/task_id=load_postgres permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T20:20:25.822064+00:00/task_id=load_postgres'
[2025-06-06T20:20:34.156+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_music_pipeline.load_postgres manual__2025-06-06T20:20:25.822064+00:00 [running]> on host 2c7dc015a251
[2025-06-06T20:20:34.214+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_music_pipeline' AIRFLOW_CTX_TASK_ID='load_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T20:20:25.822064+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T20:20:25.822064+00:00'
[2025-06-06T20:20:34.215+0000] {etl_pipeline.py:25} INFO - [START] Task: load_postgres
[2025-06-06T20:20:34.215+0000] {logging_mixin.py:188} INFO -  Error al conectar o cargar datos en PostgreSQL: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2025-06-06T20:20:34.216+0000] {etl_pipeline.py:27} INFO - [END] Task: load_postgres
[2025-06-06T20:20:34.216+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-06T20:20:34.224+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_music_pipeline, task_id=load_postgres, execution_date=20250606T202025, start_date=20250606T202034, end_date=20250606T202034
[2025-06-06T20:20:34.247+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-06T20:20:34.266+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
