[2025-06-06T18:50:37.850+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:50:34.756815+00:00/task_id=transform_spotify permission to 509
[2025-06-06T18:50:37.851+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:50:34.756815+00:00/task_id=transform_spotify permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:50:34.756815+00:00/task_id=transform_spotify'
[2025-06-06T18:50:37.869+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:50:34.756815+00:00/task_id=transform_spotify permission to 509
[2025-06-06T18:50:37.869+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:50:34.756815+00:00/task_id=transform_spotify permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:50:34.756815+00:00/task_id=transform_spotify'
[2025-06-06T18:50:37.895+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_music_pipeline.transform_spotify manual__2025-06-06T18:50:34.756815+00:00 [queued]>
[2025-06-06T18:50:37.900+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_music_pipeline.transform_spotify manual__2025-06-06T18:50:34.756815+00:00 [queued]>
[2025-06-06T18:50:37.900+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-06T18:50:37.910+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_spotify> on 2025-06-06 18:50:34.756815+00:00
[2025-06-06T18:50:37.915+0000] {standard_task_runner.py:60} INFO - Started process 1489 to run task
[2025-06-06T18:50:37.917+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_music_pipeline', 'transform_spotify', 'manual__2025-06-06T18:50:34.756815+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp1j_vjz21']
[2025-06-06T18:50:37.919+0000] {standard_task_runner.py:88} INFO - Job 49: Subtask transform_spotify
[2025-06-06T18:50:37.954+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:50:34.756815+00:00/task_id=transform_spotify permission to 509
[2025-06-06T18:50:37.954+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:50:34.756815+00:00/task_id=transform_spotify permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:50:34.756815+00:00/task_id=transform_spotify'
[2025-06-06T18:50:37.956+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_music_pipeline.transform_spotify manual__2025-06-06T18:50:34.756815+00:00 [running]> on host 3dc3cd419f05
[2025-06-06T18:50:38.012+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_music_pipeline' AIRFLOW_CTX_TASK_ID='transform_spotify' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T18:50:34.756815+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T18:50:34.756815+00:00'
[2025-06-06T18:50:38.013+0000] {etl_pipeline.py:25} INFO - [START] Task: transform_spotify
[2025-06-06T18:50:38.013+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 26, in wrapper
    result = func(*args, **kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 33, in wrapper
    func(*args, **kwargs)
TypeError: transform_spotify() got an unexpected keyword argument 'conf'
[2025-06-06T18:50:38.021+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_music_pipeline, task_id=transform_spotify, execution_date=20250606T185034, start_date=20250606T185037, end_date=20250606T185038
[2025-06-06T18:50:38.029+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 49 for task transform_spotify (transform_spotify() got an unexpected keyword argument 'conf'; 1489)
[2025-06-06T18:50:38.049+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-06T18:50:38.067+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
