[2025-06-06T19:54:20.145+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres permission to 509
[2025-06-06T19:54:20.146+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres'
[2025-06-06T19:54:20.165+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres permission to 509
[2025-06-06T19:54:20.166+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres'
[2025-06-06T19:54:20.192+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: etl_music_pipeline.load_postgres manual__2025-06-06T19:50:36.645778+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'merge_data'}
[2025-06-06T19:54:20.194+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2025-06-06T19:54:24.825+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres permission to 509
[2025-06-06T19:54:24.825+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres'
[2025-06-06T19:54:24.844+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres permission to 509
[2025-06-06T19:54:24.844+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres'
[2025-06-06T19:54:24.869+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_music_pipeline.load_postgres manual__2025-06-06T19:50:36.645778+00:00 [queued]>
[2025-06-06T19:54:24.875+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_music_pipeline.load_postgres manual__2025-06-06T19:50:36.645778+00:00 [queued]>
[2025-06-06T19:54:24.875+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-06T19:54:24.885+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_postgres> on 2025-06-06 19:50:36.645778+00:00
[2025-06-06T19:54:24.890+0000] {standard_task_runner.py:60} INFO - Started process 3040 to run task
[2025-06-06T19:54:24.891+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_music_pipeline', 'load_postgres', 'manual__2025-06-06T19:50:36.645778+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpthf_vkga']
[2025-06-06T19:54:24.893+0000] {standard_task_runner.py:88} INFO - Job 119: Subtask load_postgres
[2025-06-06T19:54:24.925+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres permission to 509
[2025-06-06T19:54:24.925+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:50:36.645778+00:00/task_id=load_postgres'
[2025-06-06T19:54:24.926+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_music_pipeline.load_postgres manual__2025-06-06T19:50:36.645778+00:00 [running]> on host 3dc3cd419f05
[2025-06-06T19:54:24.978+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_music_pipeline' AIRFLOW_CTX_TASK_ID='load_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T19:50:36.645778+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T19:50:36.645778+00:00'
[2025-06-06T19:54:24.979+0000] {etl_pipeline.py:25} INFO - [START] Task: load_postgres
[2025-06-06T19:54:24.980+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 26, in wrapper
    result = func(*args, **kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 33, in wrapper
    func(*args, **kwargs)
TypeError: load_and_store_final_dataset() got an unexpected keyword argument 'conf'
[2025-06-06T19:54:24.988+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_music_pipeline, task_id=load_postgres, execution_date=20250606T195036, start_date=20250606T195424, end_date=20250606T195424
[2025-06-06T19:54:24.995+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 119 for task load_postgres (load_and_store_final_dataset() got an unexpected keyword argument 'conf'; 3040)
[2025-06-06T19:54:25.023+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-06T19:54:25.039+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
