[2025-06-06T18:54:49.895+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:49:43.123496+00:00/task_id=transform_grammys permission to 509
[2025-06-06T18:54:49.895+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:49:43.123496+00:00/task_id=transform_grammys permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:49:43.123496+00:00/task_id=transform_grammys'
[2025-06-06T18:54:49.913+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:49:43.123496+00:00/task_id=transform_grammys permission to 509
[2025-06-06T18:54:49.914+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:49:43.123496+00:00/task_id=transform_grammys permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:49:43.123496+00:00/task_id=transform_grammys'
[2025-06-06T18:54:49.938+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_music_pipeline.transform_grammys manual__2025-06-06T18:49:43.123496+00:00 [queued]>
[2025-06-06T18:54:49.943+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_music_pipeline.transform_grammys manual__2025-06-06T18:49:43.123496+00:00 [queued]>
[2025-06-06T18:54:49.943+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-06T18:54:49.952+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_grammys> on 2025-06-06 18:49:43.123496+00:00
[2025-06-06T18:54:49.956+0000] {standard_task_runner.py:60} INFO - Started process 1647 to run task
[2025-06-06T18:54:49.958+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_music_pipeline', 'transform_grammys', 'manual__2025-06-06T18:49:43.123496+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmput_moyxx']
[2025-06-06T18:54:49.960+0000] {standard_task_runner.py:88} INFO - Job 66: Subtask transform_grammys
[2025-06-06T18:54:49.993+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:49:43.123496+00:00/task_id=transform_grammys permission to 509
[2025-06-06T18:54:49.993+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:49:43.123496+00:00/task_id=transform_grammys permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T18:49:43.123496+00:00/task_id=transform_grammys'
[2025-06-06T18:54:49.994+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_music_pipeline.transform_grammys manual__2025-06-06T18:49:43.123496+00:00 [running]> on host 3dc3cd419f05
[2025-06-06T18:54:50.049+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_music_pipeline' AIRFLOW_CTX_TASK_ID='transform_grammys' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T18:49:43.123496+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T18:49:43.123496+00:00'
[2025-06-06T18:54:50.051+0000] {etl_pipeline.py:25} INFO - [START] Task: transform_grammys
[2025-06-06T18:54:50.051+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 26, in wrapper
    result = func(*args, **kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 33, in wrapper
    func(*args, **kwargs)
TypeError: transform_grammys() got an unexpected keyword argument 'conf'
[2025-06-06T18:54:50.059+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_music_pipeline, task_id=transform_grammys, execution_date=20250606T184943, start_date=20250606T185449, end_date=20250606T185450
[2025-06-06T18:54:50.066+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 66 for task transform_grammys (transform_grammys() got an unexpected keyword argument 'conf'; 1647)
[2025-06-06T18:54:50.090+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-06T18:54:50.119+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
